### ISSUE TITLE
The dragged item not change when updating data for containerModel

### ISSUE THREAD

**Issue by hoangtuan438** [luckylooke/dragular#96]
Hi,

According to "CopyModelCtrl" in dragular-master\docs\dist\examples.js ,

I add some more codes like below to reload data in containersmodel

> var CopyModelCtrl = function ($scope, $element, dragularService) {
> 	  $scope.items1 = [{
> 	    content: 'Move me, and make copy on drop.'
> 	  }, {
> 	    content: 'If you try to drop me somewhere other than these containers, I\'ll just come back.'
> 	  }, {
> 	    content: 'Item 3'
> 	  }, {
> 	    content: 'Item 4'
> 	  }];
> 	  $scope.items2 = [{
> 	    content: 'Item 5'
> 	  }, {
> 	    content: 'Item 6'
> 	  }, {
> 	    content: 'Item 7'
> 	  }, {
> 	    content: 'Item 8'
> 	  }];
> 	  var containers = $element.children().eq(0).children();
> 	  dragularService.cleanEnviroment();
> 	  dragularService([containers[0],containers[1]],{
> 		scope: $scope,
> 	    containersModel: [$scope.items1, $scope.items2],
> 	    copy: true
> 	  });
> 	  $scope.$on('dragulardrop', function (e, el) {		
> 		e.stopPropagation();		
> 		$scope.items1 = [{
> 			content: 'sssssssssssss'
> 		  }, {
> 			content: 'cccccccccccccc'
> 		  }, {
> 			content: 'ddddddd'
> 		  }, {
> 			content: 'mmmmmmmmmmmmmmmm'
> 		  }];
> 		  
> 	  });
> 	};

But when I drag data from left to right, the data not change. it get the old data to right. here's my video about this: https://youtu.be/NgJOH6C5Rp0

Regards

**Comment by luckylooke** [comment]
Please, can you replicate your issue somewhere public? Like jsfiddle, codepen..etc.. so I can better investigate, thanks. You can reuse code from other issue like this one: https://jsfiddle.net/hLsuege1/.

**Comment by hoangtuan438** [comment]
Hi,
I just copy the code in sample of dragular. But I think I've fixed this. we have to destroy the dragular and then recreate it again.

Thanks for your attension

**Comment by luckylooke** [comment]
You dont need to destroy and recreate.. you just need to update initial model. Because dragular keeps reference to it! By `$scope.items1 = [{...` you are changing reference in scope to new array but the old one still exist in dragular reference. Instead of `$scope.items1 = [{...` you have to EDIT the array `$scope.items1.push('new item');`
